version: "3.3"
services:
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.25
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.1.4
    #user: "$UID:$GID"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    # environment:
    #   - GF_SECURITY_ADMIN_USER=grafana
    #   - GF_SECURITY_ADMIN_PASSWORD=grafana
    #   - GF_SERVER_DOMAIN=localhost
    #   - GF_USERS_ALLOW_SIGN_UP= true